import styles from "@/styles/Home.module.css";
import { publicProvider } from "@wagmi/core/providers/public";
import { Inter } from "next/font/google";
import Head from "next/head";
import { configureChains, createClient, WagmiConfig } from "wagmi";
import { goerli, localhost } from "wagmi/chains";
import { InjectedConnector } from "wagmi/connectors/injected";
import Main from "../components/main";

const inter = Inter({ subsets: ["latin"] });

const { chains, provider } = configureChains([goerli, localhost], [publicProvider()]);

const client = createClient({
  autoConnect: true,
  connectors: [new InjectedConnector({ chains })],
  provider,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <WagmiConfig client={client}>
            <Main />
          </WagmiConfig>
        </div>
      </main>
    </>
  );
}
